NAVER_CLIENT_ID=iSIp9_85FJFKnAphuUp0
NAVER_CLIENT_SECRET=ImZswJUlN1
GOOGLE_SENDER_MAIL=jaeyoon0725.utube@gmail.com
GOOGLE_APPLICATION_PASSWORD=clkxawqcomycsklx
KAKAO_CLIENT_ID=f1e15b07a4d37cb2ccfbf018617d61ea
EXPRESSWAY_ID=0597292231
NAVER_GEOCODING_CLIENT_ID=5plpv4x384
NAVER_GEOCODING_CLIENT_SECRET=uQgMo46sfa4ZWijYL54Ha5lj72ViGEQvvGhc6PAN
tmap.appkey=PKbXWIkQRR7v83eot7Kkf1IPJ7ggRxYC98sSL8CC
cctv.api.key=ed91bf31532d41bc9005d87b9834bd0e