mainpage=restinfo.action.MainpageAction
login=restinfo.action.LoginAction
register=restinfo.action.RegAction
signUp=restinfo.action.SignUpAction
emailSend=restinfo.action.EmailSendAction
emailConfirm=restinfo.action.EmailConfirmAction
kakaoMap=restinfo.action.KaKaoMapV2
restArea=restinfo.action.RestAreaAction
logout=restinfo.action.LogoutAction
naverCallback=restinfo.action.NaverCallbackAction
kakaoCallback=restinfo.action.KakaoCallbackAction
mapinfo=restinfo.action.MapInfoAction
pjyrest=restinfo.action.PjyRestAreaAction
initSARA=restinfo.action.InitAreaAction
Cctv=restinfo.action.CctvAction
getVideoUrl=restinfo.action.VideoProxyAction
restAreaDetail=restinfo.action.pjyrestAreaDetail
getStatus=restinfo.action.getStatusAction
mypage=restinfo.action.MypageAction
deleteAccount=restinfo.action.deleteAccountAction
updateProfile=restinfo.action.updateProfileAction
bookmarkdelete=restinfo.action.bookmarkdeleteAction
getRestAreaDetails=restinfo.action.getRestAreaDetailsAction
getStores=restinfo.action.getStoresAction
Members=restinfo.action.MembersAction
#Board
notice=bbs.action.NoticeAction
write=bbs.action.WriteAction
edit=bbs.action.EditAction
saveImg=bbs.action.SaveImgAction
view=bbs.action.ViewAction
del=bbs.action.DelAction
like=bbs.action.ReactionAction
hate=bbs.action.ReactionAction
searchAddress=restinfo.action.SearchAddress