mainpage=restinfo.action.MainpageAction
login=restinfo.action.LoginAction
register=restinfo.action.RegAction
#???? -??-
signUp=restinfo.action.SignUpAction
#??? -??-
emailSend=restinfo.action.EmailSendAction
emailConfirm=restinfo.action.EmailConfirmAction
test=restinfo.action.TestAction
kakaoMap=restinfo.action.KakaoMapAction