mainpage=restinfo.action.MainpageAction
login=restinfo.action.LoginAction
register=restinfo.action.RegAction

#???? -??-
signUp=restinfo.action.SignUpAction
#??? -??-
emailSend=restinfo.action.EmailSendAction
emailConfirm=restinfo.action.EmailConfirmAction
logout=restinfo.action.LogoutAction
naverCallback=restinfo.action.NaverCallbackAction
